import './globals.css';
import type { Metadata } from "next";
import { AuthProvider } from './context/authContext';
import AppContent from '@/app/components/AppContent';

export const metadata: Metadata = {
    title: "Notes App",
    description: "Generated by create next app",
};

export default function RootLayout() {
    return (
        <html lang="en">
            <body>
                <AuthProvider>
                    <AppContent />
                </AuthProvider>
            </body>
        </html>
    );
}