"use-client"
import type { Metadata } from "next";
import "./globals.css";
import Head from "next/head";
import CodingNotesList from "@/app/components/CodingNotesList";

export const metadata: Metadata = {
  title: "Notes App",
  description: "Generated by create next app",
};

interface notesDataTypes {
  name: string;
  content: string;
  id: number;
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  const notesData: notesDataTypes[] = [
    {name: "first",
      content: "First note",
      id:1},

    {name: "second",
      content: "Second note",
      id:2},
  ]
  return (
    <html lang="en">
    <Head>
        <link rel="manifest" href="./manifest.ts"/>
    </Head>
    <body
    >

      <div className="flex columns-2 gap-4 p-8">
        <CodingNotesList notesData={notesData}/>
        {children}
      </div>

    </body>
    </html>
  );
}
